apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dice
spec:
  jobTemplate:
    metadata:
      name: dice
    spec:
      backoffLimit: 25
      activeDeadlineSeconds: 20
      parallelism: 1
      completions: 1
      template:
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: dice
            resources: {}
          restartPolicy: Never
  schedule: 1 * * * *
status: {}