apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rd
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels: 
        name: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  