apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      os: ubuntu
  template:
    metadata:
      labels:
        os: ubuntu
    spec:
      volumes:
        - name: masternas-mount
          persistentVolumeClaim:
            claimName: claim-on-nas-01
      containers:
        - name: ubuntu
          image: ubuntu
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - mountPath: "/mnt/nasmount"
              name: masternas-mount
          command: ["sleep"]
          args: ["4080"]


