apiVersion: v1
kind: PersistentVolume
metadata:
  name: masternas-nfs-1gb-noslow
  labels:
    release: stable
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: slow
  nfs:
    server: 192.168.1.13
    path: "/nfs/macNFS"